# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: | 
        python -m pytest
    - name: add remote repo
      run: git remote add gandi git+ssh://${{ secrets.GANDI_SHS_USER }}@${{ secrets.GANDI_GIT_HOST }}/default.git
    - name: Push on Gandi SHS instance
      run: git push gandi master
    - name: Deploy on Gandi SHS instances deploy git through ssh
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: deploy default.git
        host: ${{ secrets.GANDI_GIT_HOST }}
        username: ${{ secrets.GANDI_SHS_USER }}
        privateKey: ${{ secrets.SSH_PV_KEY}}
